### PR TITLE
Identifiers, strings and parameters refactor

### LINKED ISSUE #205: Support raw- and byte-strings for BigQuery
Should add support for raw string literals like `R"abc+"` and byte literals `B"abc"`.

There are several other variants listed here: https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical

### LINKED ISSUE #211: Problematic regexes for detecting string tokens
There's some duplication going on and some of these regexes seem to be incorrect.

See commit comment here: https://github.com/zeroturnaround/sql-formatter/commit/4c3b35bbdbb2a87da570053490f6bca9b6761aa1#commitcomment-72847108

### LINKED ISSUE #230: [FORMATTING] Space is inserted before bracket for Map keys with . and -
\<Transferred from inferrinizzard/prettier-sql#85\>

**Describe the bug**
When formatting code with MAP keys that have `.` in them, the formatter adds a space between map name and index.

**Expected Output**
```
SELECT
    id,
    measures_map['bucket.lower'] AS bucket_lower,
    SUM(1) as cnt
FROM some.table
GROUP BY
    id,
    measures_map['bucket.lower']
```

**Actual Output**
```
SELECT
    id,
    measures_map ['bucket.lower'] AS bucket_lower,
    SUM(1) as cnt
FROM some.table
GROUP BY
   id,
   measures_map ['bucket_lower']
```

Note: if I cared about measures_map['somekey'] the formatter behaves perfectly as expected. I have not done an exhaustive search, but I see that `_` are treated correctly, but `.` and `-` are not.

**Usage**

- How are you calling / using the script? (Please provide a code snippet, if applicable)
I've tried through using `Format Document` and `Format on Save`

- What SQL language(s) does this apply to?
I'm writing in Presto/Trino and have tried `sql`, `bigquery`, `spark`, and `hive` and get the same results

- What Node version? (If applicable)
v17.9.0

### PR DESCRIPTION
**Pull request by nene**
- Separated quoted identifiers from strings.
- Separated parameter placeholders to 4 groups: positional (`?`), numbered (`:1`), named (`:name`), quoted (`:"name"`).
- Renamed `WORD` token to `IDENT` (this now includes both quoted and unquoted identifiers).
- Added `VARIABLE` token, which is used for:
    - `@name` and `@"name"` variables in MySQL/MariaDB, 
    - `&name` variables in PL/SQL,
    - `${name}` variables in Hive and Spark.
- Renamed `PLACEHOLDER` token to `PARAMETER` for consistency with the terminology elsewhere (e.g. the `params` config option).
- Overhauled the list of supported string/identifier/parameter/variable types for all languages.

The last part is not strictly backwards-compatible, mainly because lots of parameter placeholder types are no more supported for various SQL dialects.

Notably for Hive and Spark previously supported `${name}` syntax for parameters. But really these dialects don't support prepared statements at all and this `${name}` syntax is used for substitution variables which can be inserted anywhere inside SQL (e.g. inside strings). The replacement of these variables with values provided through `params` config didn't really work properly in all cases. So now these are parsed as `VARIABLE` tokens and can't be substituted through `params` config.

Removed parsing of `array[n]` and `map['key']` indexes as part of identifiers. These are now properly parsed to multiple tokens and formatted properly. But only in dialects which actually support this syntax (BigQuery, Hive, Spark).

- Fixes #211
- Fixes #205
- Fixes #230

### CODE REVIEW

File: src/core/Tokenizer.ts [hunk 1]
```diff
@@ -10,83 +10,91 @@ const toCanonicalKeyword = (text: string) => equalizeWhitespace(text.toUpperCase
...
+  numberedPlaceholderTypes?: ('?' | ':' | '$')[];
+  // Prefixes for named parameter placeholders to support, e.g. :name
+  namedPlaceholderTypes?: (':' | '@' | '$')[];
+  // Prefixes for quoted parameter placeholders to support, e.g. :"name"
+  // The type of quotes will depend on `identifierTypes` option.
+  quotedPlaceholderTypes?: (':' | '@' | '$')[];
+  // Line comment types to support, defaults to --
   lineCommentTypes?: string[];
-  specialWordChars?: { prefix?: string; any?: string; suffix?: string };
+  // Additioanl characters to support in identifiers
```
Comment (inferrinizzard) [inline src/core/Tokenizer.ts:45]: typo

File: src/languages/bigquery.formatter.ts [hunk 2]
```diff
@@ -838,10 +836,36 @@ export default class BigQueryFormatter extends Formatter {
         ...Object.values(reservedFunctions).reduce((acc, arr) => [...acc, ...arr], []),
         ...Object.values(reservedKeywords).reduce((acc, arr) => [...acc, ...arr], []),
       ]),
-      stringTypes: BigQueryFormatter.stringTypes,
-      indexedPlaceholderTypes: ['?'],
+      stringTypes: [
+        // The triple-quoted strings are listed first, so they get matched first.
+        // Otherwise the first two quotes of """ will get matched as an empty "" string.
+        '""".."""',
```
Comment (inferrinizzard) [inline src/languages/bigquery.formatter.ts:842]: can we instead pass this as something like
`{quote: '""".."""', prefixes: ['R', 'B', 'BR', 'RB']}` for each quote pattern and have the regexFactory generate all combinations + an implied case without prefixes

this is assuming there are cases in other languages where not all prefixes are exclusive

File: test/features/identifiers.ts [hunk 3]
```diff
@@ -0,0 +1,99 @@
+import { expect } from '@jest/globals';
+import dedent from 'dedent-js';
+import { FormatFn } from '../../src/sqlFormatter';
```
Comment (inferrinizzard) [inline test/features/identifiers.ts:3]: update import with absolute path

File: test/features/strings.ts [hunk 4]
```diff
@@ -54,6 +51,10 @@ export default function supportsStrings(format: FormatFn, stringTypes: string[])
           U&"update"
       `);
     });
+
+    it("detects consequitive U&'' strings as separate ones", () => {
```
Comment (inferrinizzard) [inline test/features/strings.ts:55]: typo: consecutive

File: test/features/strings.ts [hunk 5]
```diff
@@ -110,9 +81,13 @@ export default function supportsStrings(format: FormatFn, stringTypes: string[])
           N'update'
       `);
     });
+
+    it("detects consequitive N'' strings as separate ones", () => {
```
Comment (inferrinizzard) [inline test/features/strings.ts:85]: typo: consecutive

File: src/core/Tokenizer.ts [hunk 6]
```diff
@@ -10,83 +10,91 @@ const toCanonicalKeyword = (text: string) => equalizeWhitespace(text.toUpperCase
...
+  specialIdentChars?: regexFactory.IdentChars;
+  // Additional multi-character operators to support, in addition to <=, >=, <>, !=
   operators?: string[];
+  // Allows custom modifications on the token array.
+  // Called after the whole input string has been split into tokens.
+  // The result of this will be the output of the tokenizer.
   preprocess?: (tokens: Token[]) => Token[];
 }
 
+type PlaceholderPattern = { regex: RegExp; parseKey: (s: string) => string };
```
Comment (inferrinizzard) [inline src/core/Tokenizer.ts:55]: convert to interface

File: src/languages/bigquery.formatter.ts (hunk 2 above)
Comment (nene) [reply src/languages/bigquery.formatter.ts:842]: I thought of doing this, but as only BigQuery needs this ability to combine multiple prefixes, it felt simpler to just list all the combinations.

File: src/core/Tokenizer.ts (hunk 6 above)
Comment (nene) [reply src/core/Tokenizer.ts:55]: Yeah... probably better for consistency.

File: src/languages/bigquery.formatter.ts (hunk 2 above)
Comment (inferrinizzard) [reply src/languages/bigquery.formatter.ts:842]: oh yes I meant as in, list all combinations per supported quote type
so this list would look like
```
{quote: '""".."""', prefix: ['R', 'B', 'RB', 'BR'] },
{quote: "'''..'''", prefix: ['R', 'B', 'RB', 'BR'] },
{quote: '".."', prefix: ['R', 'B', 'RB', 'BR'] },
{quote: "'.."', prefix: ['R', 'B', 'RB', 'BR'] },
```
not as in give it 'R', 'B' and have it generate 'RB' and 'BR'

File: test/features/identifiers.ts [hunk 7]
```diff
@@ -0,0 +1,99 @@
...
+
+    it('no space around dot between unicode double-quoted identifiers', () => {
+      const result = format(`SELECT U&"my table".U&"col name";`);
+      expect(result).toBe(dedent`
+        SELECT
+          U&"my table".U&"col name";
+      `);
+    });
+
+    it('detects consequitive U&"" identifiers as separate ones', () => {
```
Comment (inferrinizzard) [inline test/features/identifiers.ts:74]: typo: consecutive

File: src/languages/bigquery.formatter.ts (hunk 2 above)
Comment (nene) [reply src/languages/bigquery.formatter.ts:842]: Yeah, sure, this can be easily done. I'll just need to add a function to expand:
```
{quote: '""".."""', prefix: ['R', 'B', 'RB', 'BR'] },
```

into:

```
{ quote: '""".."""' },
{ prefix: 'R', quote: '""".."""' },
{ prefix: 'B', quote: '""".."""' },
{ prefix: 'RB', quote: '""".."""' },
{ prefix: 'BR', quote: '""".."""' },
```
