### PR TITLE
Double check String types for formatter languages

### LINKED ISSUE #331: Double quotes (") in SQL fails formatting for Spark dialect
Using this module in SQL formatter in VSCode plug-in. However if a double-quote is found, the tokenizer errors Tokenizer.tokenize call with the following error
`Error: Parse error: Unexpected ""`

Formatter works when double quotes are replaced with single quotes.

### PR DESCRIPTION
**Pull request by inferrinizzard**
Resolves #331

### CODE REVIEW

File: src/languages/spark/spark.formatter.ts [hunk 1]
```diff
@@ -144,7 +144,10 @@ export default class SparkFormatter extends Formatter {
       reservedFunctionNames: functions,
       openParens: ['(', '['],
       closeParens: [')', ']'],
-      stringTypes: [{ quote: "''", prefixes: ['X'] }],
+      stringTypes: [
+        { quote: "''", prefixes: ['r'] },
+        { quote: '""', prefixes: ['r'] },
+      ],
```
Comment (nene) [inline src/languages/spark/spark.formatter.ts:150]: I see you removed the hex-strings `X. These are still supported by Spark.

I updated the docs here as well: https://github.com/sql-formatter-org/sql-formatter/wiki/Strings

Comment (inferrinizzard) [reply src/languages/spark/spark.formatter.ts:150]: missed those in the binary section

File: src/languages/mariadb/mariadb.formatter.ts [hunk 2]
```diff
@@ -268,7 +268,8 @@ export default class MariaDbFormatter extends Formatter {
       reservedLogicalOperators: ['AND', 'OR', 'XOR'],
       reservedKeywords: keywords,
       reservedFunctionNames: functions,
-      stringTypes: ['""', { quote: "''", prefixes: ['X'] }],
+      // TODO: support _ char set prefixes such as _utf8, _latin1, _binary, _utf8mb4, etc.
+      stringTypes: ['""', { quote: "''", prefixes: ['B', 'X'] }],
```
Comment (nene) [inline src/languages/mariadb/mariadb.formatter.ts:272]: Are we sure that MariaDB does not support `B""` and `X""` strings?

Should also document MariaDB `B`-strings in wiki.

File: src/languages/spark/spark.formatter.ts [hunk 3]
```diff
@@ -144,7 +144,10 @@ export default class SparkFormatter extends Formatter {
       reservedFunctionNames: functions,
       openParens: ['(', '['],
       closeParens: [')', ']'],
-      stringTypes: [{ quote: "''", prefixes: ['X'] }],
+      stringTypes: [
+        { quote: "''", prefixes: ['r', 'X'] },
+        { quote: '""', prefixes: ['r', 'X'] },
```
Comment (nene) [inline src/languages/spark/spark.formatter.ts:149]: Should use uppercase `R` prefix instead of `r` for consistency with all other prefixes configs.

File: src/languages/sql/sql.formatter.ts [hunk 4]
```diff
@@ -70,7 +70,7 @@ export default class SqlFormatter extends Formatter {
       reservedDependentClauses: ['WHEN', 'ELSE'],
       reservedKeywords: keywords,
       reservedFunctionNames: functions,
-      stringTypes: [{ quote: "''", prefixes: ['X'] }],
+      stringTypes: [{ quote: "''", prefixes: ['X', 'N'] }],
```
Comment (nene) [inline src/languages/sql/sql.formatter.ts:73]: Looks like the standard also supports `U&''` strings: https://jakewheat.github.io/sql-overview/sql-2008-foundation-grammar.html#Unicode-character-string-literal

Should also document these all in the wiki.

File: src/languages/sqlite/sqlite.formatter.ts [hunk 5]
```diff
@@ -73,7 +73,10 @@ export default class SqliteFormatter extends Formatter {
       reservedDependentClauses: ['WHEN', 'ELSE'],
       reservedKeywords: keywords,
       reservedFunctionNames: functions,
-      stringTypes: [{ quote: "''", prefixes: ['X'] }],
+      stringTypes: [
+        { quote: "''", prefixes: ['X'] },
+        { quote: '""', prefixes: ['X'] },
```
Comment (nene) [inline src/languages/sqlite/sqlite.formatter.ts:78]: Should not add `""` strings to SQLite - that will conflict with `""`-quoted identifiers.

Looks like SQLite has some strange rules where it sometimes treats double-quoted text as an identifier and sometimes as a string. And vice versa with single quotes. See: https://www.sqlite.org/lang_keywords.html

**Comment by nene** [comment]
Additionally, would be nice to have all these additional string types be covered by tests.

**Comment by inferrinizzard** [comment]
will update wiki _after_ code changes are merged, tests to come

File: src/languages/db2/db2.formatter.ts [hunk 6]
```diff
@@ -177,7 +177,7 @@ export default class Db2Formatter extends Formatter {
       reservedDependentClauses: ['WHEN', 'ELSE', 'ELSEIF'],
       reservedKeywords: keywords,
       reservedFunctionNames: functions,
-      stringTypes: [{ quote: "''", prefixes: ['X', 'G', 'N', 'GX', 'UX', 'U&'] }],
+      stringTypes: [{ quote: "''", prefixes: ['G', 'N', 'X', 'BX', 'GX', 'UX', 'U&'] }],
```
[the remark this answers is not in the document]
Comment (inferrinizzard) [reply src/languages/db2/db2.formatter.ts:180]: https://www.ibm.com/docs/en/db2-for-zos/11?topic=constants-binary-string

File: src/languages/mariadb/mariadb.formatter.ts (hunk 2 above)
Comment (inferrinizzard) [reply src/languages/mariadb/mariadb.formatter.ts:272]: all the examples use single quotes but double quote strings are mentioned in 1 line in the MariaDB docs
so presumably they are compatible, will update
